package inventariodemaf;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author gonzz
 */
public class frmLogin extends javax.swing.JFrame {

    String mUsuario;
    String mPass;
    
    public static boolean mEsAdmin;
    public static boolean mEsEncargadoPEP;

    public static ArrayList<Usuario> mListaDeUsuarios = new ArrayList();
    public static ArrayList<Rol> mListaDeRoles = new ArrayList(); 

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        

        //Creacion de rol administrador por medio de código
        Rol rolAdministrador = new Rol();
        rolAdministrador.setNombre("Administrador");
        rolAdministrador.setDescripcion("Este rol permite mostrar la sección de roles, de usuario, estadísticas y productos.");

        //Creación de rol vendedor
        Rol rolEncargadoPEP = new Rol();
        rolEncargadoPEP.setNombre("Vendedor");
        rolEncargadoPEP.setDescripcion("Este rol permite ver la sección de productos.");
        
        mListaDeRoles.add(rolAdministrador);
        mListaDeRoles.add(rolEncargadoPEP);

        //Listas de roles
        
        ArrayList<Rol> listaRolesParaMaster = new ArrayList();
        
        listaRolesParaMaster.add(rolAdministrador);
        listaRolesParaMaster.add(rolEncargadoPEP);

        ArrayList<Rol> listaRolesParaAdmin = new ArrayList();
        listaRolesParaAdmin.add(rolAdministrador);

        ArrayList<Rol> listaRolesParaEncargadoPEP = new ArrayList();
        listaRolesParaEncargadoPEP.add(rolEncargadoPEP);
        
        //Vamos a crear un usuario por defecto. Se va a llamar Gonz y tendrá como contraseña Gonz
        Usuario usuario1 = new Usuario();
        usuario1.setNombre("Gonz");
        usuario1.setPass("Gonz");
        usuario1.setListaRoles(listaRolesParaMaster);

        Usuario usuario2 = new Usuario();
        usuario2.setNombre("Mauricio");
        usuario2.setPass("Mauricio");
        usuario2.setListaRoles(listaRolesParaAdmin);

        Usuario usuario3 = new Usuario();
        usuario3.setNombre("Diana");
        usuario3.setPass("Diana");
        usuario3.setListaRoles(listaRolesParaEncargadoPEP);

        //Vamos a agregar el usuario por defecto a la lista de Usuarios (este va a existir siempre que el programa corra)
        mListaDeUsuarios.add(usuario1);
        mListaDeUsuarios.add(usuario2);
        mListaDeUsuarios.add(usuario3);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelAzul = new javax.swing.JPanel();
        panelBlanco = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JToggleButton();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        panelAzul.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout panelAzulLayout = new javax.swing.GroupLayout(panelAzul);
        panelAzul.setLayout(panelAzulLayout);
        panelAzulLayout.setHorizontalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        panelAzulLayout.setVerticalGroup(
            panelAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        panelBlanco.setBackground(new java.awt.Color(255, 255, 255));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario");

        lblPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPass.setText("Contraseña");

        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnIngresar.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBlancoLayout = new javax.swing.GroupLayout(panelBlanco);
        panelBlanco.setLayout(panelBlancoLayout);
        panelBlancoLayout.setHorizontalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPass)
                    .addComponent(lblUsuario))
                .addGap(63, 63, 63)
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtPass))
                .addGap(81, 81, 81))
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBlancoLayout.setVerticalGroup(
            panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panelBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBlanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBlanco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:

        obtenerCredenciales();

        //Previo a comprobar roles
        boolean puedeEntrar = this.comprobarCredenciales();
//        
        if (puedeEntrar) {

            frmMenuPrincipal FrmMenuPrincipal = new frmMenuPrincipal();
            FrmMenuPrincipal.setVisible(true);
            
//            this.mostrarFormularioSegunRol();
//            //Mostrar la siguiente pantalla  
//            JOptionPane.showMessageDialog(this, "Usuario y contraseña correctos.");
//            frmMenuPrincipal menuPrincipal = new frmMenuPrincipal();
//            menuPrincipal.setVisible(true);
//            
        } else {

            JOptionPane.showMessageDialog(this, "Usuario no existe o contraseña incorrecta");

        }
//        //Otra forma de hacer sesion
//        if (mUsuario.equals("Gonz") && mPass.equals("Gonz")){
//            
//            JOptionPane.showMessageDialog(this, "Usuario y contraseña correctos.");
//            frmMenuPrincipal menuPrincipal = new frmMenuPrincipal();
//            menuPrincipal.setVisible(true);
//            
//        }else
//        
//            JOptionPane.showMessageDialog(this,"Usuario no existe o contraseña incorrecta");

    }                                           

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    private boolean comprobarCredenciales() {
        //Recorrer la lista de usuarios para ver que el usuario exista y pueda ingresar al sistema
        boolean credencialesCorrectas = false;
        mEsEncargadoPEP = false;
        mEsAdmin = false;

        Iterator<Usuario> iterador = mListaDeUsuarios.iterator();

        while (iterador.hasNext()) {

            Usuario tmpUsuario = iterador.next();

            if (tmpUsuario.getNombre().equals(mUsuario) && tmpUsuario.getPass().equals(mPass)) {

                Iterator<Rol> iteradorRol = tmpUsuario.getListaRoles().iterator();

                while (iteradorRol.hasNext()) {

                    Rol tmpRol = iteradorRol.next();
                    if (tmpRol.getNombre().equals("Administrador")) {

                        mEsAdmin = true;

                    } else if (tmpRol.getNombre().equals("Vendedor")) {

                        mEsEncargadoPEP = true;

                    }

                }

                credencialesCorrectas = true;
                break;

            }
        }
        return credencialesCorrectas;
    }

    private void obtenerCredenciales() {
        mUsuario = txtUsuario.getText();
        mPass = new String(txtPass.getPassword());
    }

//    private void mostrarFormularioSegunRol() {
//
//        if (mEsAdmin && mEsEncargadoPEP) {
//            //Mostrar pantallas con menú de administrador y vendedor
//            frmMenuPrincipalMaster frmAdminVendedor = new frmMenuPrincipalMaster();
//            frmAdminVendedor.setVisible(true);
//            
//        } else if (mEsEncargadoPEP) {
//            //Mostrar con los menús de encargado productos en proceso
//            
//            frmMenuPrincipalEncargadoPEP frmVendedor = new frmMenuPrincipalEncargadoPEP();
//            frmVendedor.setVisible(true);
//            
//        }else if (mEsAdmin){
//            //Mostrar menús de administrador
//            
//            frmMenuPrincipalAdmin frmAdmin = new frmMenuPrincipalAdmin();
//            frmAdmin.setVisible(true);
//            
//        }

//    }


    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton btnIngresar;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelAzul;
    private javax.swing.JPanel panelBlanco;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration                   
}
